/** Shared design tokens — keep in sync with :root in index.css */
export const ds = {
  navy: '#0f1c2e',
  primary: '#2563eb',
  primaryHover: '#1d4ed8',
  bg: '#f1f5f9',
  bgSoft: '#f8fafc',
  surface: '#ffffff',
  border: '#e2e8f0',
  text: '#0f172a',
  textSecondary: '#64748b',
  textMuted: '#94a3b8',
  radius: 10,
  radiusSm: 8,
  radiusLg: 12,
  radiusXl: 14,
  shadow: '0 1px 2px rgba(15, 23, 42, 0.05)',
  shadowSoft: '0 1px 3px rgba(15, 23, 42, 0.06), 0 1px 2px rgba(15, 23, 42, 0.04)',
  green: '#16a34a',
  greenSoft: '#ecfdf5',
  teal: '#0d9488',
  tealSoft: '#ccfbf1',
  purple: '#7c3aed',
  purpleSoft: '#ede9fe',
  amber: '#d97706',
  amberSoft: '#fef3c7',
  red: '#7A1528',
  redSoft: '#F9F0F2',
  blueSoft: '#eff6ff',
  filterPanel: '#f8fbff',
} as const;

export const antThemeToken = {
  colorPrimary: ds.primary,
  colorInfo: ds.primary,
  colorSuccess: ds.green,
  colorWarning: ds.amber,
  colorError: ds.red,
  borderRadius: ds.radiusSm,
  borderRadiusLG: ds.radiusLg,
  fontFamily:
    "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif",
  fontWeightStrong: 700,
  colorBgLayout: ds.bg,
  colorBgContainer: ds.surface,
  colorBorder: ds.border,
  colorText: ds.text,
  colorTextSecondary: ds.textSecondary,
  colorTextTertiary: ds.textMuted,
  controlHeight: 36,
  controlOutline: 'rgba(37, 99, 235, 0.2)',
  boxShadow: ds.shadow,
  boxShadowSecondary: ds.shadowSoft,
} as const;
